# Generated by Django 4.2.1 on 2026-05-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва характеристики/мітки')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_anc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supports_custom_eq',
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.feature', verbose_name='Мітки/Характеристики'),
        ),
    ]
